# Ubuntu 18.04 (Bionic Beaver) support
sudo: required
dist: bionic

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang++-8
      env: COMPILER=clang++-8
before_install:
  - sudo apt-get update -qq

install:

script:
  - make CC=$COMPILER all
